include $(APPDIR)/Make.defs

PROGNAME  = txts_test
PRIORITY  = 100
STACKSIZE = $(CONFIG_DEFAULT_TASK_STACKSIZE)
MODULE    = $(CONFIG_EXAMPLES_TXTS_TEST)

MAINSRC = txts_test_main.c

include $(APPDIR)/Application.mk
